// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package com.classmeteo.ws;

public interface ClassMeteoFluxesWS extends java.rmi.Remote {
	public com.classmeteo.ws.TranslationWS getBarometricTranslation(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.ClimatologyWS[] getClimatologyDay(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.ClimatologyWS[] getClimatologyDayToDate(java.lang.String arg0, java.lang.Long arg1) throws java.rmi.RemoteException;

	public com.classmeteo.ws.ClimatologyWS[] getClimatologyDayToDayNum(java.lang.String arg0, java.lang.Integer arg1) throws java.rmi.RemoteException;

	public com.classmeteo.ws.ClimatologyWS[] getClimatologyMonth(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.TranslationWS getCountriesTranslation(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.CurrentCondWS getCurrentByLocId(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.CustomData1[] getCurrentConditionsByCoordinates(java.lang.Float arg0, java.lang.Float arg1, java.lang.Float arg2, java.lang.Float arg3, java.lang.String arg4) throws java.rmi.RemoteException;

	public com.classmeteo.ws.DailyForecastWS[] getDailyByLocId(java.lang.String arg0, java.lang.String arg1) throws java.rmi.RemoteException;

	public com.classmeteo.ws.TranslationWS getDayNamesTranslation(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.CustomData1[] getEuropeWeatherLocations() throws java.rmi.RemoteException;

	public com.classmeteo.ws.TranslationWS getForecastPhrasesTranslation(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.HourlyForecastWS[] getHourlyByLocId(java.lang.String arg0, java.lang.String arg1) throws java.rmi.RemoteException;

	public com.classmeteo.ws.IntradayForecastWS[] getIntraDayByLocId(java.lang.String arg0, java.lang.String arg1) throws java.rmi.RemoteException;

	public com.classmeteo.ws.CustomData1[] getItalyWeatherLocations() throws java.rmi.RemoteException;

	public com.classmeteo.ws.MasterLocWS[] getLocByCity(java.lang.String arg0, java.lang.String arg1) throws java.rmi.RemoteException;

	public com.classmeteo.ws.MasterLocWS getLocByZipCode(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.TranslationWS getLocationsTranslation(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.MasterLocWS[] getMasterLocByEuropeCityName(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.MasterLocWS[] getMasterLocByItalianCityName(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.MasterLocWS getMasterLocByLocId(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.MasterLocList getMasterLocByNameLike(java.lang.String arg0, java.lang.Integer arg1) throws java.rmi.RemoteException;

	public com.classmeteo.ws.MasterLocList getNearestMasterLoc(java.lang.Float arg0, java.lang.Float arg1, java.lang.Integer arg2) throws java.rmi.RemoteException;

	public com.classmeteo.ws.HourlyForecastWS[] getNextHourlyByLocId(java.lang.String arg0, java.lang.String arg1) throws java.rmi.RemoteException;

	public com.classmeteo.ws.TranslationWS getObservationTranslation(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.CustomData1[] getSkiByCoordinates(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) throws java.rmi.RemoteException;

	public com.classmeteo.ws.CustomData1[] getSkiGroupByCoordinates(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, java.lang.String arg5) throws java.rmi.RemoteException;

	public com.classmeteo.ws.TranslationWS getStatesTranslation(java.lang.String arg0) throws java.rmi.RemoteException;

	public java.lang.String getTest() throws java.rmi.RemoteException;

	public com.classmeteo.ws.TranslationWS getTimeZoneTranslation(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.TranslationWS getUVIndexTranslation(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.DailyForecastWS[] getWeekEndByLocId(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.TranslationWS getWindTranslation(java.lang.String arg0) throws java.rmi.RemoteException;

	public com.classmeteo.ws.CustomData1[] getWorldWeatherLocations() throws java.rmi.RemoteException;

	public com.classmeteo.ws.TranslationWS getZipCodeTranslation(java.lang.String arg0) throws java.rmi.RemoteException;

}
