// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class CustomData1 {
    protected java.lang.String cityNm;
    protected java.lang.String lat;
    protected java.lang.String locId;
    protected java.lang.String longo;
    protected java.lang.String reserved_1;
    protected java.lang.String skiId;
    protected java.lang.String sky;
    protected java.lang.String sunrise;
    protected java.lang.String sunset;
    protected java.lang.String tmpC;
    protected java.lang.String uvIdx;
    protected java.lang.String wx;
    protected java.lang.String hIC;
    protected java.lang.String wSpdK;
    
    public CustomData1() {
    }
    
    public CustomData1(java.lang.String cityNm, java.lang.String lat, java.lang.String locId, java.lang.String longo, java.lang.String reserved_1, java.lang.String skiId, java.lang.String sky, java.lang.String sunrise, java.lang.String sunset, java.lang.String tmpC, java.lang.String uvIdx, java.lang.String wx, java.lang.String hIC, java.lang.String wSpdK) {
        this.cityNm = cityNm;
        this.lat = lat;
        this.locId = locId;
        this.longo = longo;
        this.reserved_1 = reserved_1;
        this.skiId = skiId;
        this.sky = sky;
        this.sunrise = sunrise;
        this.sunset = sunset;
        this.tmpC = tmpC;
        this.uvIdx = uvIdx;
        this.wx = wx;
        this.hIC = hIC;
        this.wSpdK = wSpdK;
    }
    
    public java.lang.String getCityNm() {
        return cityNm;
    }
    
    public void setCityNm(java.lang.String cityNm) {
        this.cityNm = cityNm;
    }
    
    public java.lang.String getLat() {
        return lat;
    }
    
    public void setLat(java.lang.String lat) {
        this.lat = lat;
    }
    
    public java.lang.String getLocId() {
        return locId;
    }
    
    public void setLocId(java.lang.String locId) {
        this.locId = locId;
    }
    
    public java.lang.String getLongo() {
        return longo;
    }
    
    public void setLongo(java.lang.String longo) {
        this.longo = longo;
    }
    
    public java.lang.String getReserved_1() {
        return reserved_1;
    }
    
    public void setReserved_1(java.lang.String reserved_1) {
        this.reserved_1 = reserved_1;
    }
    
    public java.lang.String getSkiId() {
        return skiId;
    }
    
    public void setSkiId(java.lang.String skiId) {
        this.skiId = skiId;
    }
    
    public java.lang.String getSky() {
        return sky;
    }
    
    public void setSky(java.lang.String sky) {
        this.sky = sky;
    }
    
    public java.lang.String getSunrise() {
        return sunrise;
    }
    
    public void setSunrise(java.lang.String sunrise) {
        this.sunrise = sunrise;
    }
    
    public java.lang.String getSunset() {
        return sunset;
    }
    
    public void setSunset(java.lang.String sunset) {
        this.sunset = sunset;
    }
    
    public java.lang.String getTmpC() {
        return tmpC;
    }
    
    public void setTmpC(java.lang.String tmpC) {
        this.tmpC = tmpC;
    }
    
    public java.lang.String getUvIdx() {
        return uvIdx;
    }
    
    public void setUvIdx(java.lang.String uvIdx) {
        this.uvIdx = uvIdx;
    }
    
    public java.lang.String getWx() {
        return wx;
    }
    
    public void setWx(java.lang.String wx) {
        this.wx = wx;
    }
    
    public java.lang.String getHIC() {
        return hIC;
    }
    
    public void setHIC(java.lang.String hIC) {
        this.hIC = hIC;
    }
    
    public java.lang.String getWSpdK() {
        return wSpdK;
    }
    
    public void setWSpdK(java.lang.String wSpdK) {
        this.wSpdK = wSpdK;
    }
}
