// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class DailyForecastWS {
    protected java.lang.String CPOS12;
    protected java.lang.String CPOS1224;
    protected java.lang.String clds12;
    protected java.lang.String clds1224;
    protected com.classmeteo.ws.DailyForecastPKWS dailyForecastPK;
    protected java.lang.String dow;
    protected java.lang.String fcstValDay;
    protected java.lang.String fcstValGMT;
    protected java.lang.String glfCat;
    protected java.lang.String glfIdx;
    protected java.lang.String HIC;
    protected java.lang.String HIF;
    protected java.lang.String hiTmpC;
    protected java.lang.String hiTmpF;
    protected java.lang.String loTmpC;
    protected java.lang.String loTmpF;
    protected java.lang.String locValDay;
    protected java.lang.String locValTm;
    protected java.lang.String mnRise;
    protected java.lang.String mnSet;
    protected java.lang.String POP12;
    protected java.lang.String POP1224;
    protected java.lang.String POP24;
    protected java.lang.String procTm;
    protected java.lang.String qpf;
    protected java.lang.String qpf12;
    protected java.lang.String qpf1224;
    protected java.lang.String RH12;
    protected java.lang.String RH1224;
    protected java.lang.String shrtCst;
    protected java.lang.String sky;
    protected java.lang.String sky12;
    protected java.lang.String sky1224;
    protected java.lang.String sky1224X;
    protected java.lang.String sky12X;
    protected java.lang.String skyX;
    protected java.lang.String snsblWx;
    protected java.lang.String snsblWx12;
    protected java.lang.String snsblWx1224;
    protected java.lang.String snwQpf;
    protected java.lang.String snwQpf12;
    protected java.lang.String snwQpf1224;
    protected java.lang.String stnNm;
    protected java.lang.String sunrise;
    protected java.lang.String sunset;
    protected java.lang.String TSnsblWx;
    protected java.lang.String TSnsblWx12;
    protected java.lang.String TSnsblWx1224;
    protected java.lang.String uvDes;
    protected java.lang.String uvIdx;
    protected java.lang.String uvIdxRw;
    protected java.lang.String uvWrn;
    protected java.lang.String WCC;
    protected java.lang.String WCC12;
    protected java.lang.String WCC1224;
    protected java.lang.String WCF;
    protected java.lang.String WCF12;
    protected java.lang.String WCF1224;
    protected java.lang.String WDir12;
    protected java.lang.String WDir1224;
    protected java.lang.String WDirAsc12;
    protected java.lang.String WDirAsc1224;
    protected java.lang.String WSpdK12;
    protected java.lang.String WSpdK1224;
    protected java.lang.String WSpdKn12;
    protected java.lang.String WSpdKn1224;
    protected java.lang.String WSpdM12;
    protected java.lang.String WSpdM1224;
    protected java.lang.String wrlsWx;
    protected java.lang.String wrlsWx12;
    protected java.lang.String wrlsWx1224;
    
    public DailyForecastWS() {
    }
    
    public DailyForecastWS(java.lang.String CPOS12, java.lang.String CPOS1224, java.lang.String clds12, java.lang.String clds1224, com.classmeteo.ws.DailyForecastPKWS dailyForecastPK, java.lang.String dow, java.lang.String fcstValDay, java.lang.String fcstValGMT, java.lang.String glfCat, java.lang.String glfIdx, java.lang.String HIC, java.lang.String HIF, java.lang.String hiTmpC, java.lang.String hiTmpF, java.lang.String loTmpC, java.lang.String loTmpF, java.lang.String locValDay, java.lang.String locValTm, java.lang.String mnRise, java.lang.String mnSet, java.lang.String POP12, java.lang.String POP1224, java.lang.String POP24, java.lang.String procTm, java.lang.String qpf, java.lang.String qpf12, java.lang.String qpf1224, java.lang.String RH12, java.lang.String RH1224, java.lang.String shrtCst, java.lang.String sky, java.lang.String sky12, java.lang.String sky1224, java.lang.String sky1224X, java.lang.String sky12X, java.lang.String skyX, java.lang.String snsblWx, java.lang.String snsblWx12, java.lang.String snsblWx1224, java.lang.String snwQpf, java.lang.String snwQpf12, java.lang.String snwQpf1224, java.lang.String stnNm, java.lang.String sunrise, java.lang.String sunset, java.lang.String TSnsblWx, java.lang.String TSnsblWx12, java.lang.String TSnsblWx1224, java.lang.String uvDes, java.lang.String uvIdx, java.lang.String uvIdxRw, java.lang.String uvWrn, java.lang.String WCC, java.lang.String WCC12, java.lang.String WCC1224, java.lang.String WCF, java.lang.String WCF12, java.lang.String WCF1224, java.lang.String WDir12, java.lang.String WDir1224, java.lang.String WDirAsc12, java.lang.String WDirAsc1224, java.lang.String WSpdK12, java.lang.String WSpdK1224, java.lang.String WSpdKn12, java.lang.String WSpdKn1224, java.lang.String WSpdM12, java.lang.String WSpdM1224, java.lang.String wrlsWx, java.lang.String wrlsWx12, java.lang.String wrlsWx1224) {
        this.CPOS12 = CPOS12;
        this.CPOS1224 = CPOS1224;
        this.clds12 = clds12;
        this.clds1224 = clds1224;
        this.dailyForecastPK = dailyForecastPK;
        this.dow = dow;
        this.fcstValDay = fcstValDay;
        this.fcstValGMT = fcstValGMT;
        this.glfCat = glfCat;
        this.glfIdx = glfIdx;
        this.HIC = HIC;
        this.HIF = HIF;
        this.hiTmpC = hiTmpC;
        this.hiTmpF = hiTmpF;
        this.loTmpC = loTmpC;
        this.loTmpF = loTmpF;
        this.locValDay = locValDay;
        this.locValTm = locValTm;
        this.mnRise = mnRise;
        this.mnSet = mnSet;
        this.POP12 = POP12;
        this.POP1224 = POP1224;
        this.POP24 = POP24;
        this.procTm = procTm;
        this.qpf = qpf;
        this.qpf12 = qpf12;
        this.qpf1224 = qpf1224;
        this.RH12 = RH12;
        this.RH1224 = RH1224;
        this.shrtCst = shrtCst;
        this.sky = sky;
        this.sky12 = sky12;
        this.sky1224 = sky1224;
        this.sky1224X = sky1224X;
        this.sky12X = sky12X;
        this.skyX = skyX;
        this.snsblWx = snsblWx;
        this.snsblWx12 = snsblWx12;
        this.snsblWx1224 = snsblWx1224;
        this.snwQpf = snwQpf;
        this.snwQpf12 = snwQpf12;
        this.snwQpf1224 = snwQpf1224;
        this.stnNm = stnNm;
        this.sunrise = sunrise;
        this.sunset = sunset;
        this.TSnsblWx = TSnsblWx;
        this.TSnsblWx12 = TSnsblWx12;
        this.TSnsblWx1224 = TSnsblWx1224;
        this.uvDes = uvDes;
        this.uvIdx = uvIdx;
        this.uvIdxRw = uvIdxRw;
        this.uvWrn = uvWrn;
        this.WCC = WCC;
        this.WCC12 = WCC12;
        this.WCC1224 = WCC1224;
        this.WCF = WCF;
        this.WCF12 = WCF12;
        this.WCF1224 = WCF1224;
        this.WDir12 = WDir12;
        this.WDir1224 = WDir1224;
        this.WDirAsc12 = WDirAsc12;
        this.WDirAsc1224 = WDirAsc1224;
        this.WSpdK12 = WSpdK12;
        this.WSpdK1224 = WSpdK1224;
        this.WSpdKn12 = WSpdKn12;
        this.WSpdKn1224 = WSpdKn1224;
        this.WSpdM12 = WSpdM12;
        this.WSpdM1224 = WSpdM1224;
        this.wrlsWx = wrlsWx;
        this.wrlsWx12 = wrlsWx12;
        this.wrlsWx1224 = wrlsWx1224;
    }
    
    public java.lang.String getCPOS12() {
        return CPOS12;
    }
    
    public void setCPOS12(java.lang.String CPOS12) {
        this.CPOS12 = CPOS12;
    }
    
    public java.lang.String getCPOS1224() {
        return CPOS1224;
    }
    
    public void setCPOS1224(java.lang.String CPOS1224) {
        this.CPOS1224 = CPOS1224;
    }
    
    public java.lang.String getClds12() {
        return clds12;
    }
    
    public void setClds12(java.lang.String clds12) {
        this.clds12 = clds12;
    }
    
    public java.lang.String getClds1224() {
        return clds1224;
    }
    
    public void setClds1224(java.lang.String clds1224) {
        this.clds1224 = clds1224;
    }
    
    public com.classmeteo.ws.DailyForecastPKWS getDailyForecastPK() {
        return dailyForecastPK;
    }
    
    public void setDailyForecastPK(com.classmeteo.ws.DailyForecastPKWS dailyForecastPK) {
        this.dailyForecastPK = dailyForecastPK;
    }
    
    public java.lang.String getDow() {
        return dow;
    }
    
    public void setDow(java.lang.String dow) {
        this.dow = dow;
    }
    
    public java.lang.String getFcstValDay() {
        return fcstValDay;
    }
    
    public void setFcstValDay(java.lang.String fcstValDay) {
        this.fcstValDay = fcstValDay;
    }
    
    public java.lang.String getFcstValGMT() {
        return fcstValGMT;
    }
    
    public void setFcstValGMT(java.lang.String fcstValGMT) {
        this.fcstValGMT = fcstValGMT;
    }
    
    public java.lang.String getGlfCat() {
        return glfCat;
    }
    
    public void setGlfCat(java.lang.String glfCat) {
        this.glfCat = glfCat;
    }
    
    public java.lang.String getGlfIdx() {
        return glfIdx;
    }
    
    public void setGlfIdx(java.lang.String glfIdx) {
        this.glfIdx = glfIdx;
    }
    
    public java.lang.String getHIC() {
        return HIC;
    }
    
    public void setHIC(java.lang.String HIC) {
        this.HIC = HIC;
    }
    
    public java.lang.String getHIF() {
        return HIF;
    }
    
    public void setHIF(java.lang.String HIF) {
        this.HIF = HIF;
    }
    
    public java.lang.String getHiTmpC() {
        return hiTmpC;
    }
    
    public void setHiTmpC(java.lang.String hiTmpC) {
        this.hiTmpC = hiTmpC;
    }
    
    public java.lang.String getHiTmpF() {
        return hiTmpF;
    }
    
    public void setHiTmpF(java.lang.String hiTmpF) {
        this.hiTmpF = hiTmpF;
    }
    
    public java.lang.String getLoTmpC() {
        return loTmpC;
    }
    
    public void setLoTmpC(java.lang.String loTmpC) {
        this.loTmpC = loTmpC;
    }
    
    public java.lang.String getLoTmpF() {
        return loTmpF;
    }
    
    public void setLoTmpF(java.lang.String loTmpF) {
        this.loTmpF = loTmpF;
    }
    
    public java.lang.String getLocValDay() {
        return locValDay;
    }
    
    public void setLocValDay(java.lang.String locValDay) {
        this.locValDay = locValDay;
    }
    
    public java.lang.String getLocValTm() {
        return locValTm;
    }
    
    public void setLocValTm(java.lang.String locValTm) {
        this.locValTm = locValTm;
    }
    
    public java.lang.String getMnRise() {
        return mnRise;
    }
    
    public void setMnRise(java.lang.String mnRise) {
        this.mnRise = mnRise;
    }
    
    public java.lang.String getMnSet() {
        return mnSet;
    }
    
    public void setMnSet(java.lang.String mnSet) {
        this.mnSet = mnSet;
    }
    
    public java.lang.String getPOP12() {
        return POP12;
    }
    
    public void setPOP12(java.lang.String POP12) {
        this.POP12 = POP12;
    }
    
    public java.lang.String getPOP1224() {
        return POP1224;
    }
    
    public void setPOP1224(java.lang.String POP1224) {
        this.POP1224 = POP1224;
    }
    
    public java.lang.String getPOP24() {
        return POP24;
    }
    
    public void setPOP24(java.lang.String POP24) {
        this.POP24 = POP24;
    }
    
    public java.lang.String getProcTm() {
        return procTm;
    }
    
    public void setProcTm(java.lang.String procTm) {
        this.procTm = procTm;
    }
    
    public java.lang.String getQpf() {
        return qpf;
    }
    
    public void setQpf(java.lang.String qpf) {
        this.qpf = qpf;
    }
    
    public java.lang.String getQpf12() {
        return qpf12;
    }
    
    public void setQpf12(java.lang.String qpf12) {
        this.qpf12 = qpf12;
    }
    
    public java.lang.String getQpf1224() {
        return qpf1224;
    }
    
    public void setQpf1224(java.lang.String qpf1224) {
        this.qpf1224 = qpf1224;
    }
    
    public java.lang.String getRH12() {
        return RH12;
    }
    
    public void setRH12(java.lang.String RH12) {
        this.RH12 = RH12;
    }
    
    public java.lang.String getRH1224() {
        return RH1224;
    }
    
    public void setRH1224(java.lang.String RH1224) {
        this.RH1224 = RH1224;
    }
    
    public java.lang.String getShrtCst() {
        return shrtCst;
    }
    
    public void setShrtCst(java.lang.String shrtCst) {
        this.shrtCst = shrtCst;
    }
    
    public java.lang.String getSky() {
        return sky;
    }
    
    public void setSky(java.lang.String sky) {
        this.sky = sky;
    }
    
    public java.lang.String getSky12() {
        return sky12;
    }
    
    public void setSky12(java.lang.String sky12) {
        this.sky12 = sky12;
    }
    
    public java.lang.String getSky1224() {
        return sky1224;
    }
    
    public void setSky1224(java.lang.String sky1224) {
        this.sky1224 = sky1224;
    }
    
    public java.lang.String getSky1224X() {
        return sky1224X;
    }
    
    public void setSky1224X(java.lang.String sky1224X) {
        this.sky1224X = sky1224X;
    }
    
    public java.lang.String getSky12X() {
        return sky12X;
    }
    
    public void setSky12X(java.lang.String sky12X) {
        this.sky12X = sky12X;
    }
    
    public java.lang.String getSkyX() {
        return skyX;
    }
    
    public void setSkyX(java.lang.String skyX) {
        this.skyX = skyX;
    }
    
    public java.lang.String getSnsblWx() {
        return snsblWx;
    }
    
    public void setSnsblWx(java.lang.String snsblWx) {
        this.snsblWx = snsblWx;
    }
    
    public java.lang.String getSnsblWx12() {
        return snsblWx12;
    }
    
    public void setSnsblWx12(java.lang.String snsblWx12) {
        this.snsblWx12 = snsblWx12;
    }
    
    public java.lang.String getSnsblWx1224() {
        return snsblWx1224;
    }
    
    public void setSnsblWx1224(java.lang.String snsblWx1224) {
        this.snsblWx1224 = snsblWx1224;
    }
    
    public java.lang.String getSnwQpf() {
        return snwQpf;
    }
    
    public void setSnwQpf(java.lang.String snwQpf) {
        this.snwQpf = snwQpf;
    }
    
    public java.lang.String getSnwQpf12() {
        return snwQpf12;
    }
    
    public void setSnwQpf12(java.lang.String snwQpf12) {
        this.snwQpf12 = snwQpf12;
    }
    
    public java.lang.String getSnwQpf1224() {
        return snwQpf1224;
    }
    
    public void setSnwQpf1224(java.lang.String snwQpf1224) {
        this.snwQpf1224 = snwQpf1224;
    }
    
    public java.lang.String getStnNm() {
        return stnNm;
    }
    
    public void setStnNm(java.lang.String stnNm) {
        this.stnNm = stnNm;
    }
    
    public java.lang.String getSunrise() {
        return sunrise;
    }
    
    public void setSunrise(java.lang.String sunrise) {
        this.sunrise = sunrise;
    }
    
    public java.lang.String getSunset() {
        return sunset;
    }
    
    public void setSunset(java.lang.String sunset) {
        this.sunset = sunset;
    }
    
    public java.lang.String getTSnsblWx() {
        return TSnsblWx;
    }
    
    public void setTSnsblWx(java.lang.String TSnsblWx) {
        this.TSnsblWx = TSnsblWx;
    }
    
    public java.lang.String getTSnsblWx12() {
        return TSnsblWx12;
    }
    
    public void setTSnsblWx12(java.lang.String TSnsblWx12) {
        this.TSnsblWx12 = TSnsblWx12;
    }
    
    public java.lang.String getTSnsblWx1224() {
        return TSnsblWx1224;
    }
    
    public void setTSnsblWx1224(java.lang.String TSnsblWx1224) {
        this.TSnsblWx1224 = TSnsblWx1224;
    }
    
    public java.lang.String getUvDes() {
        return uvDes;
    }
    
    public void setUvDes(java.lang.String uvDes) {
        this.uvDes = uvDes;
    }
    
    public java.lang.String getUvIdx() {
        return uvIdx;
    }
    
    public void setUvIdx(java.lang.String uvIdx) {
        this.uvIdx = uvIdx;
    }
    
    public java.lang.String getUvIdxRw() {
        return uvIdxRw;
    }
    
    public void setUvIdxRw(java.lang.String uvIdxRw) {
        this.uvIdxRw = uvIdxRw;
    }
    
    public java.lang.String getUvWrn() {
        return uvWrn;
    }
    
    public void setUvWrn(java.lang.String uvWrn) {
        this.uvWrn = uvWrn;
    }
    
    public java.lang.String getWCC() {
        return WCC;
    }
    
    public void setWCC(java.lang.String WCC) {
        this.WCC = WCC;
    }
    
    public java.lang.String getWCC12() {
        return WCC12;
    }
    
    public void setWCC12(java.lang.String WCC12) {
        this.WCC12 = WCC12;
    }
    
    public java.lang.String getWCC1224() {
        return WCC1224;
    }
    
    public void setWCC1224(java.lang.String WCC1224) {
        this.WCC1224 = WCC1224;
    }
    
    public java.lang.String getWCF() {
        return WCF;
    }
    
    public void setWCF(java.lang.String WCF) {
        this.WCF = WCF;
    }
    
    public java.lang.String getWCF12() {
        return WCF12;
    }
    
    public void setWCF12(java.lang.String WCF12) {
        this.WCF12 = WCF12;
    }
    
    public java.lang.String getWCF1224() {
        return WCF1224;
    }
    
    public void setWCF1224(java.lang.String WCF1224) {
        this.WCF1224 = WCF1224;
    }
    
    public java.lang.String getWDir12() {
        return WDir12;
    }
    
    public void setWDir12(java.lang.String WDir12) {
        this.WDir12 = WDir12;
    }
    
    public java.lang.String getWDir1224() {
        return WDir1224;
    }
    
    public void setWDir1224(java.lang.String WDir1224) {
        this.WDir1224 = WDir1224;
    }
    
    public java.lang.String getWDirAsc12() {
        return WDirAsc12;
    }
    
    public void setWDirAsc12(java.lang.String WDirAsc12) {
        this.WDirAsc12 = WDirAsc12;
    }
    
    public java.lang.String getWDirAsc1224() {
        return WDirAsc1224;
    }
    
    public void setWDirAsc1224(java.lang.String WDirAsc1224) {
        this.WDirAsc1224 = WDirAsc1224;
    }
    
    public java.lang.String getWSpdK12() {
        return WSpdK12;
    }
    
    public void setWSpdK12(java.lang.String WSpdK12) {
        this.WSpdK12 = WSpdK12;
    }
    
    public java.lang.String getWSpdK1224() {
        return WSpdK1224;
    }
    
    public void setWSpdK1224(java.lang.String WSpdK1224) {
        this.WSpdK1224 = WSpdK1224;
    }
    
    public java.lang.String getWSpdKn12() {
        return WSpdKn12;
    }
    
    public void setWSpdKn12(java.lang.String WSpdKn12) {
        this.WSpdKn12 = WSpdKn12;
    }
    
    public java.lang.String getWSpdKn1224() {
        return WSpdKn1224;
    }
    
    public void setWSpdKn1224(java.lang.String WSpdKn1224) {
        this.WSpdKn1224 = WSpdKn1224;
    }
    
    public java.lang.String getWSpdM12() {
        return WSpdM12;
    }
    
    public void setWSpdM12(java.lang.String WSpdM12) {
        this.WSpdM12 = WSpdM12;
    }
    
    public java.lang.String getWSpdM1224() {
        return WSpdM1224;
    }
    
    public void setWSpdM1224(java.lang.String WSpdM1224) {
        this.WSpdM1224 = WSpdM1224;
    }
    
    public java.lang.String getWrlsWx() {
        return wrlsWx;
    }
    
    public void setWrlsWx(java.lang.String wrlsWx) {
        this.wrlsWx = wrlsWx;
    }
    
    public java.lang.String getWrlsWx12() {
        return wrlsWx12;
    }
    
    public void setWrlsWx12(java.lang.String wrlsWx12) {
        this.wrlsWx12 = wrlsWx12;
    }
    
    public java.lang.String getWrlsWx1224() {
        return wrlsWx1224;
    }
    
    public void setWrlsWx1224(java.lang.String wrlsWx1224) {
        this.wrlsWx1224 = wrlsWx1224;
    }
}
