// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class GetSkiByCoordinates {
    protected java.lang.String arg0;
    protected java.lang.String arg1;
    protected java.lang.String arg2;
    protected java.lang.String arg3;
    
    public GetSkiByCoordinates() {
    }
    
    public GetSkiByCoordinates(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) {
        this.arg0 = arg0;
        this.arg1 = arg1;
        this.arg2 = arg2;
        this.arg3 = arg3;
    }
    
    public java.lang.String getArg0() {
        return arg0;
    }
    
    public void setArg0(java.lang.String arg0) {
        this.arg0 = arg0;
    }
    
    public java.lang.String getArg1() {
        return arg1;
    }
    
    public void setArg1(java.lang.String arg1) {
        this.arg1 = arg1;
    }
    
    public java.lang.String getArg2() {
        return arg2;
    }
    
    public void setArg2(java.lang.String arg2) {
        this.arg2 = arg2;
    }
    
    public java.lang.String getArg3() {
        return arg3;
    }
    
    public void setArg3(java.lang.String arg3) {
        this.arg3 = arg3;
    }
}
