// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class GetWindTranslationResponse {
    protected com.classmeteo.ws.TranslationWS _return;
    
    public GetWindTranslationResponse() {
    }
    
    public GetWindTranslationResponse(com.classmeteo.ws.TranslationWS _return) {
        this._return = _return;
    }
    
    public com.classmeteo.ws.TranslationWS get_return() {
        return _return;
    }
    
    public void set_return(com.classmeteo.ws.TranslationWS _return) {
        this._return = _return;
    }
}
