// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class MasterLocWS {
    protected java.lang.Integer active;
    protected java.lang.String arptId;
    protected java.lang.String cityNm;
    protected java.lang.String cliStn;
    protected java.lang.String clsRad;
    protected java.lang.String cntryCd;
    protected java.lang.String cntyFips;
    protected java.lang.String cntyId;
    protected java.lang.String cntyNm;
    protected java.lang.String coopId;
    protected java.lang.String dmaCd;
    protected java.lang.String dySTAct;
    protected java.lang.String dySTInd;
    protected java.lang.String elev;
    protected java.lang.String epaId;
    protected java.lang.String gmtDiff;
    protected java.lang.String idxId;
    protected java.lang.String lat;
    protected java.lang.Float latd;
    protected java.lang.String locId;
    protected java.lang.String locType;
    protected java.lang.Float longd;
    protected java.lang.String longo;
    protected java.lang.String lsRad;
    protected java.lang.String metRad;
    protected java.lang.String mrnZoneId;
    protected java.lang.String obsStn;
    protected java.lang.String pllnId;
    protected java.lang.String primTecci;
    protected java.lang.String procTm;
    protected java.lang.String prsntNm;
    protected java.lang.String regSat;
    protected java.lang.String secObsStn;
    protected java.lang.String secTecci;
    protected java.lang.String siteId;
    protected java.lang.String skiId;
    protected java.lang.String ssRad;
    protected java.lang.String stCd;
    protected java.lang.String tertObsStn;
    protected java.lang.String tertTecci;
    protected java.lang.String tideId;
    protected java.lang.String tmZnAbbr;
    protected java.lang.String tmZnNm;
    protected java.lang.String ultRad;
    protected java.lang.String zip2LocId;
    protected java.lang.String zoneId;
    protected java.lang.String zoneNm;
    
    public MasterLocWS() {
    }
    
    public MasterLocWS(java.lang.Integer active, java.lang.String arptId, java.lang.String cityNm, java.lang.String cliStn, java.lang.String clsRad, java.lang.String cntryCd, java.lang.String cntyFips, java.lang.String cntyId, java.lang.String cntyNm, java.lang.String coopId, java.lang.String dmaCd, java.lang.String dySTAct, java.lang.String dySTInd, java.lang.String elev, java.lang.String epaId, java.lang.String gmtDiff, java.lang.String idxId, java.lang.String lat, java.lang.Float latd, java.lang.String locId, java.lang.String locType, java.lang.Float longd, java.lang.String longo, java.lang.String lsRad, java.lang.String metRad, java.lang.String mrnZoneId, java.lang.String obsStn, java.lang.String pllnId, java.lang.String primTecci, java.lang.String procTm, java.lang.String prsntNm, java.lang.String regSat, java.lang.String secObsStn, java.lang.String secTecci, java.lang.String siteId, java.lang.String skiId, java.lang.String ssRad, java.lang.String stCd, java.lang.String tertObsStn, java.lang.String tertTecci, java.lang.String tideId, java.lang.String tmZnAbbr, java.lang.String tmZnNm, java.lang.String ultRad, java.lang.String zip2LocId, java.lang.String zoneId, java.lang.String zoneNm) {
        this.active = active;
        this.arptId = arptId;
        this.cityNm = cityNm;
        this.cliStn = cliStn;
        this.clsRad = clsRad;
        this.cntryCd = cntryCd;
        this.cntyFips = cntyFips;
        this.cntyId = cntyId;
        this.cntyNm = cntyNm;
        this.coopId = coopId;
        this.dmaCd = dmaCd;
        this.dySTAct = dySTAct;
        this.dySTInd = dySTInd;
        this.elev = elev;
        this.epaId = epaId;
        this.gmtDiff = gmtDiff;
        this.idxId = idxId;
        this.lat = lat;
        this.latd = latd;
        this.locId = locId;
        this.locType = locType;
        this.longd = longd;
        this.longo = longo;
        this.lsRad = lsRad;
        this.metRad = metRad;
        this.mrnZoneId = mrnZoneId;
        this.obsStn = obsStn;
        this.pllnId = pllnId;
        this.primTecci = primTecci;
        this.procTm = procTm;
        this.prsntNm = prsntNm;
        this.regSat = regSat;
        this.secObsStn = secObsStn;
        this.secTecci = secTecci;
        this.siteId = siteId;
        this.skiId = skiId;
        this.ssRad = ssRad;
        this.stCd = stCd;
        this.tertObsStn = tertObsStn;
        this.tertTecci = tertTecci;
        this.tideId = tideId;
        this.tmZnAbbr = tmZnAbbr;
        this.tmZnNm = tmZnNm;
        this.ultRad = ultRad;
        this.zip2LocId = zip2LocId;
        this.zoneId = zoneId;
        this.zoneNm = zoneNm;
    }
    
    public java.lang.Integer getActive() {
        return active;
    }
    
    public void setActive(java.lang.Integer active) {
        this.active = active;
    }
    
    public java.lang.String getArptId() {
        return arptId;
    }
    
    public void setArptId(java.lang.String arptId) {
        this.arptId = arptId;
    }
    
    public java.lang.String getCityNm() {
        return cityNm;
    }
    
    public void setCityNm(java.lang.String cityNm) {
        this.cityNm = cityNm;
    }
    
    public java.lang.String getCliStn() {
        return cliStn;
    }
    
    public void setCliStn(java.lang.String cliStn) {
        this.cliStn = cliStn;
    }
    
    public java.lang.String getClsRad() {
        return clsRad;
    }
    
    public void setClsRad(java.lang.String clsRad) {
        this.clsRad = clsRad;
    }
    
    public java.lang.String getCntryCd() {
        return cntryCd;
    }
    
    public void setCntryCd(java.lang.String cntryCd) {
        this.cntryCd = cntryCd;
    }
    
    public java.lang.String getCntyFips() {
        return cntyFips;
    }
    
    public void setCntyFips(java.lang.String cntyFips) {
        this.cntyFips = cntyFips;
    }
    
    public java.lang.String getCntyId() {
        return cntyId;
    }
    
    public void setCntyId(java.lang.String cntyId) {
        this.cntyId = cntyId;
    }
    
    public java.lang.String getCntyNm() {
        return cntyNm;
    }
    
    public void setCntyNm(java.lang.String cntyNm) {
        this.cntyNm = cntyNm;
    }
    
    public java.lang.String getCoopId() {
        return coopId;
    }
    
    public void setCoopId(java.lang.String coopId) {
        this.coopId = coopId;
    }
    
    public java.lang.String getDmaCd() {
        return dmaCd;
    }
    
    public void setDmaCd(java.lang.String dmaCd) {
        this.dmaCd = dmaCd;
    }
    
    public java.lang.String getDySTAct() {
        return dySTAct;
    }
    
    public void setDySTAct(java.lang.String dySTAct) {
        this.dySTAct = dySTAct;
    }
    
    public java.lang.String getDySTInd() {
        return dySTInd;
    }
    
    public void setDySTInd(java.lang.String dySTInd) {
        this.dySTInd = dySTInd;
    }
    
    public java.lang.String getElev() {
        return elev;
    }
    
    public void setElev(java.lang.String elev) {
        this.elev = elev;
    }
    
    public java.lang.String getEpaId() {
        return epaId;
    }
    
    public void setEpaId(java.lang.String epaId) {
        this.epaId = epaId;
    }
    
    public java.lang.String getGmtDiff() {
        return gmtDiff;
    }
    
    public void setGmtDiff(java.lang.String gmtDiff) {
        this.gmtDiff = gmtDiff;
    }
    
    public java.lang.String getIdxId() {
        return idxId;
    }
    
    public void setIdxId(java.lang.String idxId) {
        this.idxId = idxId;
    }
    
    public java.lang.String getLat() {
        return lat;
    }
    
    public void setLat(java.lang.String lat) {
        this.lat = lat;
    }
    
    public java.lang.Float getLatd() {
        return latd;
    }
    
    public void setLatd(java.lang.Float latd) {
        this.latd = latd;
    }
    
    public java.lang.String getLocId() {
        return locId;
    }
    
    public void setLocId(java.lang.String locId) {
        this.locId = locId;
    }
    
    public java.lang.String getLocType() {
        return locType;
    }
    
    public void setLocType(java.lang.String locType) {
        this.locType = locType;
    }
    
    public java.lang.Float getLongd() {
        return longd;
    }
    
    public void setLongd(java.lang.Float longd) {
        this.longd = longd;
    }
    
    public java.lang.String getLongo() {
        return longo;
    }
    
    public void setLongo(java.lang.String longo) {
        this.longo = longo;
    }
    
    public java.lang.String getLsRad() {
        return lsRad;
    }
    
    public void setLsRad(java.lang.String lsRad) {
        this.lsRad = lsRad;
    }
    
    public java.lang.String getMetRad() {
        return metRad;
    }
    
    public void setMetRad(java.lang.String metRad) {
        this.metRad = metRad;
    }
    
    public java.lang.String getMrnZoneId() {
        return mrnZoneId;
    }
    
    public void setMrnZoneId(java.lang.String mrnZoneId) {
        this.mrnZoneId = mrnZoneId;
    }
    
    public java.lang.String getObsStn() {
        return obsStn;
    }
    
    public void setObsStn(java.lang.String obsStn) {
        this.obsStn = obsStn;
    }
    
    public java.lang.String getPllnId() {
        return pllnId;
    }
    
    public void setPllnId(java.lang.String pllnId) {
        this.pllnId = pllnId;
    }
    
    public java.lang.String getPrimTecci() {
        return primTecci;
    }
    
    public void setPrimTecci(java.lang.String primTecci) {
        this.primTecci = primTecci;
    }
    
    public java.lang.String getProcTm() {
        return procTm;
    }
    
    public void setProcTm(java.lang.String procTm) {
        this.procTm = procTm;
    }
    
    public java.lang.String getPrsntNm() {
        return prsntNm;
    }
    
    public void setPrsntNm(java.lang.String prsntNm) {
        this.prsntNm = prsntNm;
    }
    
    public java.lang.String getRegSat() {
        return regSat;
    }
    
    public void setRegSat(java.lang.String regSat) {
        this.regSat = regSat;
    }
    
    public java.lang.String getSecObsStn() {
        return secObsStn;
    }
    
    public void setSecObsStn(java.lang.String secObsStn) {
        this.secObsStn = secObsStn;
    }
    
    public java.lang.String getSecTecci() {
        return secTecci;
    }
    
    public void setSecTecci(java.lang.String secTecci) {
        this.secTecci = secTecci;
    }
    
    public java.lang.String getSiteId() {
        return siteId;
    }
    
    public void setSiteId(java.lang.String siteId) {
        this.siteId = siteId;
    }
    
    public java.lang.String getSkiId() {
        return skiId;
    }
    
    public void setSkiId(java.lang.String skiId) {
        this.skiId = skiId;
    }
    
    public java.lang.String getSsRad() {
        return ssRad;
    }
    
    public void setSsRad(java.lang.String ssRad) {
        this.ssRad = ssRad;
    }
    
    public java.lang.String getStCd() {
        return stCd;
    }
    
    public void setStCd(java.lang.String stCd) {
        this.stCd = stCd;
    }
    
    public java.lang.String getTertObsStn() {
        return tertObsStn;
    }
    
    public void setTertObsStn(java.lang.String tertObsStn) {
        this.tertObsStn = tertObsStn;
    }
    
    public java.lang.String getTertTecci() {
        return tertTecci;
    }
    
    public void setTertTecci(java.lang.String tertTecci) {
        this.tertTecci = tertTecci;
    }
    
    public java.lang.String getTideId() {
        return tideId;
    }
    
    public void setTideId(java.lang.String tideId) {
        this.tideId = tideId;
    }
    
    public java.lang.String getTmZnAbbr() {
        return tmZnAbbr;
    }
    
    public void setTmZnAbbr(java.lang.String tmZnAbbr) {
        this.tmZnAbbr = tmZnAbbr;
    }
    
    public java.lang.String getTmZnNm() {
        return tmZnNm;
    }
    
    public void setTmZnNm(java.lang.String tmZnNm) {
        this.tmZnNm = tmZnNm;
    }
    
    public java.lang.String getUltRad() {
        return ultRad;
    }
    
    public void setUltRad(java.lang.String ultRad) {
        this.ultRad = ultRad;
    }
    
    public java.lang.String getZip2LocId() {
        return zip2LocId;
    }
    
    public void setZip2LocId(java.lang.String zip2LocId) {
        this.zip2LocId = zip2LocId;
    }
    
    public java.lang.String getZoneId() {
        return zoneId;
    }
    
    public void setZoneId(java.lang.String zoneId) {
        this.zoneId = zoneId;
    }
    
    public java.lang.String getZoneNm() {
        return zoneNm;
    }
    
    public void setZoneNm(java.lang.String zoneNm) {
        this.zoneNm = zoneNm;
    }
}
