// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class MasterLocList {
    protected com.classmeteo.ws.MasterLocWS[] locations;
    
    public MasterLocList() {
    }
    
    public MasterLocList(com.classmeteo.ws.MasterLocWS[] locations) {
        this.locations = locations;
    }
    
    public com.classmeteo.ws.MasterLocWS[] getLocations() {
        return locations;
    }
    
    public void setLocations(com.classmeteo.ws.MasterLocWS[] locations) {
        this.locations = locations;
    }
}
