// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class TranslationPKWS {
    protected java.lang.String keyP;
    protected java.lang.String typeP;
    
    public TranslationPKWS() {
    }
    
    public TranslationPKWS(java.lang.String keyP, java.lang.String typeP) {
        this.keyP = keyP;
        this.typeP = typeP;
    }
    
    public java.lang.String getKeyP() {
        return keyP;
    }
    
    public void setKeyP(java.lang.String keyP) {
        this.keyP = keyP;
    }
    
    public java.lang.String getTypeP() {
        return typeP;
    }
    
    public void setTypeP(java.lang.String typeP) {
        this.typeP = typeP;
    }
}
