// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class TranslationWS {
    protected java.lang.String barometricPressure;
    protected java.lang.String countriesAbbr;
    protected java.lang.String countriesPresnt;
    protected java.lang.String countriesUppercase;
    protected java.lang.String dayNm;
    protected java.lang.String direzVentoLong;
    protected java.lang.String forecastLongDesc;
    protected java.lang.String forecastShortDesc;
    protected java.lang.String locationPresnt;
    protected java.lang.String locationUppercase;
    protected java.lang.String observtnLongDesc;
    protected java.lang.String paeseName;
    protected java.lang.String paeseNameUppercase;
    protected java.lang.String stateCode;
    protected java.lang.String stateName;
    protected java.lang.String timezoneAbbrDst;
    protected java.lang.String timezoneAbbrStd;
    protected java.lang.String timezoneNmDst;
    protected java.lang.String timezoneNmStd;
    protected com.classmeteo.ws.TranslationPKWS translationPK;
    protected java.lang.String uvLongDesc;
    
    public TranslationWS() {
    }
    
    public TranslationWS(java.lang.String barometricPressure, java.lang.String countriesAbbr, java.lang.String countriesPresnt, java.lang.String countriesUppercase, java.lang.String dayNm, java.lang.String direzVentoLong, java.lang.String forecastLongDesc, java.lang.String forecastShortDesc, java.lang.String locationPresnt, java.lang.String locationUppercase, java.lang.String observtnLongDesc, java.lang.String paeseName, java.lang.String paeseNameUppercase, java.lang.String stateCode, java.lang.String stateName, java.lang.String timezoneAbbrDst, java.lang.String timezoneAbbrStd, java.lang.String timezoneNmDst, java.lang.String timezoneNmStd, com.classmeteo.ws.TranslationPKWS translationPK, java.lang.String uvLongDesc) {
        this.barometricPressure = barometricPressure;
        this.countriesAbbr = countriesAbbr;
        this.countriesPresnt = countriesPresnt;
        this.countriesUppercase = countriesUppercase;
        this.dayNm = dayNm;
        this.direzVentoLong = direzVentoLong;
        this.forecastLongDesc = forecastLongDesc;
        this.forecastShortDesc = forecastShortDesc;
        this.locationPresnt = locationPresnt;
        this.locationUppercase = locationUppercase;
        this.observtnLongDesc = observtnLongDesc;
        this.paeseName = paeseName;
        this.paeseNameUppercase = paeseNameUppercase;
        this.stateCode = stateCode;
        this.stateName = stateName;
        this.timezoneAbbrDst = timezoneAbbrDst;
        this.timezoneAbbrStd = timezoneAbbrStd;
        this.timezoneNmDst = timezoneNmDst;
        this.timezoneNmStd = timezoneNmStd;
        this.translationPK = translationPK;
        this.uvLongDesc = uvLongDesc;
    }
    
    public java.lang.String getBarometricPressure() {
        return barometricPressure;
    }
    
    public void setBarometricPressure(java.lang.String barometricPressure) {
        this.barometricPressure = barometricPressure;
    }
    
    public java.lang.String getCountriesAbbr() {
        return countriesAbbr;
    }
    
    public void setCountriesAbbr(java.lang.String countriesAbbr) {
        this.countriesAbbr = countriesAbbr;
    }
    
    public java.lang.String getCountriesPresnt() {
        return countriesPresnt;
    }
    
    public void setCountriesPresnt(java.lang.String countriesPresnt) {
        this.countriesPresnt = countriesPresnt;
    }
    
    public java.lang.String getCountriesUppercase() {
        return countriesUppercase;
    }
    
    public void setCountriesUppercase(java.lang.String countriesUppercase) {
        this.countriesUppercase = countriesUppercase;
    }
    
    public java.lang.String getDayNm() {
        return dayNm;
    }
    
    public void setDayNm(java.lang.String dayNm) {
        this.dayNm = dayNm;
    }
    
    public java.lang.String getDirezVentoLong() {
        return direzVentoLong;
    }
    
    public void setDirezVentoLong(java.lang.String direzVentoLong) {
        this.direzVentoLong = direzVentoLong;
    }
    
    public java.lang.String getForecastLongDesc() {
        return forecastLongDesc;
    }
    
    public void setForecastLongDesc(java.lang.String forecastLongDesc) {
        this.forecastLongDesc = forecastLongDesc;
    }
    
    public java.lang.String getForecastShortDesc() {
        return forecastShortDesc;
    }
    
    public void setForecastShortDesc(java.lang.String forecastShortDesc) {
        this.forecastShortDesc = forecastShortDesc;
    }
    
    public java.lang.String getLocationPresnt() {
        return locationPresnt;
    }
    
    public void setLocationPresnt(java.lang.String locationPresnt) {
        this.locationPresnt = locationPresnt;
    }
    
    public java.lang.String getLocationUppercase() {
        return locationUppercase;
    }
    
    public void setLocationUppercase(java.lang.String locationUppercase) {
        this.locationUppercase = locationUppercase;
    }
    
    public java.lang.String getObservtnLongDesc() {
        return observtnLongDesc;
    }
    
    public void setObservtnLongDesc(java.lang.String observtnLongDesc) {
        this.observtnLongDesc = observtnLongDesc;
    }
    
    public java.lang.String getPaeseName() {
        return paeseName;
    }
    
    public void setPaeseName(java.lang.String paeseName) {
        this.paeseName = paeseName;
    }
    
    public java.lang.String getPaeseNameUppercase() {
        return paeseNameUppercase;
    }
    
    public void setPaeseNameUppercase(java.lang.String paeseNameUppercase) {
        this.paeseNameUppercase = paeseNameUppercase;
    }
    
    public java.lang.String getStateCode() {
        return stateCode;
    }
    
    public void setStateCode(java.lang.String stateCode) {
        this.stateCode = stateCode;
    }
    
    public java.lang.String getStateName() {
        return stateName;
    }
    
    public void setStateName(java.lang.String stateName) {
        this.stateName = stateName;
    }
    
    public java.lang.String getTimezoneAbbrDst() {
        return timezoneAbbrDst;
    }
    
    public void setTimezoneAbbrDst(java.lang.String timezoneAbbrDst) {
        this.timezoneAbbrDst = timezoneAbbrDst;
    }
    
    public java.lang.String getTimezoneAbbrStd() {
        return timezoneAbbrStd;
    }
    
    public void setTimezoneAbbrStd(java.lang.String timezoneAbbrStd) {
        this.timezoneAbbrStd = timezoneAbbrStd;
    }
    
    public java.lang.String getTimezoneNmDst() {
        return timezoneNmDst;
    }
    
    public void setTimezoneNmDst(java.lang.String timezoneNmDst) {
        this.timezoneNmDst = timezoneNmDst;
    }
    
    public java.lang.String getTimezoneNmStd() {
        return timezoneNmStd;
    }
    
    public void setTimezoneNmStd(java.lang.String timezoneNmStd) {
        this.timezoneNmStd = timezoneNmStd;
    }
    
    public com.classmeteo.ws.TranslationPKWS getTranslationPK() {
        return translationPK;
    }
    
    public void setTranslationPK(com.classmeteo.ws.TranslationPKWS translationPK) {
        this.translationPK = translationPK;
    }
    
    public java.lang.String getUvLongDesc() {
        return uvLongDesc;
    }
    
    public void setUvLongDesc(java.lang.String uvLongDesc) {
        this.uvLongDesc = uvLongDesc;
    }
}
