// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class ClimatologyWS {
    protected java.lang.Long climoDate;
    protected java.lang.String climoInterval;
    protected java.lang.String climoStn;
    protected java.lang.String climoStnNm;
    protected java.lang.Float hiC;
    protected java.lang.Float hiF;
    protected java.lang.Integer idClimatology;
    protected java.lang.Float loC;
    protected java.lang.Float loF;
    protected java.lang.Float meanC;
    protected java.lang.Float meanF;
    protected java.lang.Float precipCm;
    protected java.lang.Float precipIn;
    protected java.lang.Float recordHiC;
    protected java.lang.Long recordHiDt;
    protected java.lang.Float recordHiF;
    protected java.lang.Float recordLoC;
    protected java.lang.Long recordLoDt;
    protected java.lang.Float recordLoF;
    protected java.lang.Float snowCm;
    protected java.lang.Float snowIn;
    
    public ClimatologyWS() {
    }
    
    public ClimatologyWS(java.lang.Long climoDate, java.lang.String climoInterval, java.lang.String climoStn, java.lang.String climoStnNm, java.lang.Float hiC, java.lang.Float hiF, java.lang.Integer idClimatology, java.lang.Float loC, java.lang.Float loF, java.lang.Float meanC, java.lang.Float meanF, java.lang.Float precipCm, java.lang.Float precipIn, java.lang.Float recordHiC, java.lang.Long recordHiDt, java.lang.Float recordHiF, java.lang.Float recordLoC, java.lang.Long recordLoDt, java.lang.Float recordLoF, java.lang.Float snowCm, java.lang.Float snowIn) {
        this.climoDate = climoDate;
        this.climoInterval = climoInterval;
        this.climoStn = climoStn;
        this.climoStnNm = climoStnNm;
        this.hiC = hiC;
        this.hiF = hiF;
        this.idClimatology = idClimatology;
        this.loC = loC;
        this.loF = loF;
        this.meanC = meanC;
        this.meanF = meanF;
        this.precipCm = precipCm;
        this.precipIn = precipIn;
        this.recordHiC = recordHiC;
        this.recordHiDt = recordHiDt;
        this.recordHiF = recordHiF;
        this.recordLoC = recordLoC;
        this.recordLoDt = recordLoDt;
        this.recordLoF = recordLoF;
        this.snowCm = snowCm;
        this.snowIn = snowIn;
    }
    
    public java.lang.Long getClimoDate() {
        return climoDate;
    }
    
    public void setClimoDate(java.lang.Long climoDate) {
        this.climoDate = climoDate;
    }
    
    public java.lang.String getClimoInterval() {
        return climoInterval;
    }
    
    public void setClimoInterval(java.lang.String climoInterval) {
        this.climoInterval = climoInterval;
    }
    
    public java.lang.String getClimoStn() {
        return climoStn;
    }
    
    public void setClimoStn(java.lang.String climoStn) {
        this.climoStn = climoStn;
    }
    
    public java.lang.String getClimoStnNm() {
        return climoStnNm;
    }
    
    public void setClimoStnNm(java.lang.String climoStnNm) {
        this.climoStnNm = climoStnNm;
    }
    
    public java.lang.Float getHiC() {
        return hiC;
    }
    
    public void setHiC(java.lang.Float hiC) {
        this.hiC = hiC;
    }
    
    public java.lang.Float getHiF() {
        return hiF;
    }
    
    public void setHiF(java.lang.Float hiF) {
        this.hiF = hiF;
    }
    
    public java.lang.Integer getIdClimatology() {
        return idClimatology;
    }
    
    public void setIdClimatology(java.lang.Integer idClimatology) {
        this.idClimatology = idClimatology;
    }
    
    public java.lang.Float getLoC() {
        return loC;
    }
    
    public void setLoC(java.lang.Float loC) {
        this.loC = loC;
    }
    
    public java.lang.Float getLoF() {
        return loF;
    }
    
    public void setLoF(java.lang.Float loF) {
        this.loF = loF;
    }
    
    public java.lang.Float getMeanC() {
        return meanC;
    }
    
    public void setMeanC(java.lang.Float meanC) {
        this.meanC = meanC;
    }
    
    public java.lang.Float getMeanF() {
        return meanF;
    }
    
    public void setMeanF(java.lang.Float meanF) {
        this.meanF = meanF;
    }
    
    public java.lang.Float getPrecipCm() {
        return precipCm;
    }
    
    public void setPrecipCm(java.lang.Float precipCm) {
        this.precipCm = precipCm;
    }
    
    public java.lang.Float getPrecipIn() {
        return precipIn;
    }
    
    public void setPrecipIn(java.lang.Float precipIn) {
        this.precipIn = precipIn;
    }
    
    public java.lang.Float getRecordHiC() {
        return recordHiC;
    }
    
    public void setRecordHiC(java.lang.Float recordHiC) {
        this.recordHiC = recordHiC;
    }
    
    public java.lang.Long getRecordHiDt() {
        return recordHiDt;
    }
    
    public void setRecordHiDt(java.lang.Long recordHiDt) {
        this.recordHiDt = recordHiDt;
    }
    
    public java.lang.Float getRecordHiF() {
        return recordHiF;
    }
    
    public void setRecordHiF(java.lang.Float recordHiF) {
        this.recordHiF = recordHiF;
    }
    
    public java.lang.Float getRecordLoC() {
        return recordLoC;
    }
    
    public void setRecordLoC(java.lang.Float recordLoC) {
        this.recordLoC = recordLoC;
    }
    
    public java.lang.Long getRecordLoDt() {
        return recordLoDt;
    }
    
    public void setRecordLoDt(java.lang.Long recordLoDt) {
        this.recordLoDt = recordLoDt;
    }
    
    public java.lang.Float getRecordLoF() {
        return recordLoF;
    }
    
    public void setRecordLoF(java.lang.Float recordLoF) {
        this.recordLoF = recordLoF;
    }
    
    public java.lang.Float getSnowCm() {
        return snowCm;
    }
    
    public void setSnowCm(java.lang.Float snowCm) {
        this.snowCm = snowCm;
    }
    
    public java.lang.Float getSnowIn() {
        return snowIn;
    }
    
    public void setSnowIn(java.lang.Float snowIn) {
        this.snowIn = snowIn;
    }
}
