// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class GetCurrentConditionsByCoordinates {
    protected java.lang.Float arg0;
    protected java.lang.Float arg1;
    protected java.lang.Float arg2;
    protected java.lang.Float arg3;
    protected java.lang.String arg4;
    
    public GetCurrentConditionsByCoordinates() {
    }
    
    public GetCurrentConditionsByCoordinates(java.lang.Float arg0, java.lang.Float arg1, java.lang.Float arg2, java.lang.Float arg3, java.lang.String arg4) {
        this.arg0 = arg0;
        this.arg1 = arg1;
        this.arg2 = arg2;
        this.arg3 = arg3;
        this.arg4 = arg4;
    }
    
    public java.lang.Float getArg0() {
        return arg0;
    }
    
    public void setArg0(java.lang.Float arg0) {
        this.arg0 = arg0;
    }
    
    public java.lang.Float getArg1() {
        return arg1;
    }
    
    public void setArg1(java.lang.Float arg1) {
        this.arg1 = arg1;
    }
    
    public java.lang.Float getArg2() {
        return arg2;
    }
    
    public void setArg2(java.lang.Float arg2) {
        this.arg2 = arg2;
    }
    
    public java.lang.Float getArg3() {
        return arg3;
    }
    
    public void setArg3(java.lang.Float arg3) {
        this.arg3 = arg3;
    }
    
    public java.lang.String getArg4() {
        return arg4;
    }
    
    public void setArg4(java.lang.String arg4) {
        this.arg4 = arg4;
    }
}
