// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class GetClimatologyDayToDayNumResponse {
    protected com.classmeteo.ws.ClimatologyWS[] _return;
    
    public GetClimatologyDayToDayNumResponse() {
    }
    
    public GetClimatologyDayToDayNumResponse(com.classmeteo.ws.ClimatologyWS[] _return) {
        this._return = _return;
    }
    
    public com.classmeteo.ws.ClimatologyWS[] get_return() {
        return _return;
    }
    
    public void set_return(com.classmeteo.ws.ClimatologyWS[] _return) {
        this._return = _return;
    }
}
