// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class GetClimatologyDayToDayNum {
    protected java.lang.String arg0;
    protected java.lang.Integer arg1;
    
    public GetClimatologyDayToDayNum() {
    }
    
    public GetClimatologyDayToDayNum(java.lang.String arg0, java.lang.Integer arg1) {
        this.arg0 = arg0;
        this.arg1 = arg1;
    }
    
    public java.lang.String getArg0() {
        return arg0;
    }
    
    public void setArg0(java.lang.String arg0) {
        this.arg0 = arg0;
    }
    
    public java.lang.Integer getArg1() {
        return arg1;
    }
    
    public void setArg1(java.lang.Integer arg1) {
        this.arg1 = arg1;
    }
}
