// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class GetDayNamesTranslation {
    protected java.lang.String arg0;
    
    public GetDayNamesTranslation() {
    }
    
    public GetDayNamesTranslation(java.lang.String arg0) {
        this.arg0 = arg0;
    }
    
    public java.lang.String getArg0() {
        return arg0;
    }
    
    public void setArg0(java.lang.String arg0) {
        this.arg0 = arg0;
    }
}
