// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class GetNearestMasterLoc {
    protected java.lang.Float arg0;
    protected java.lang.Float arg1;
    protected java.lang.Integer arg2;
    
    public GetNearestMasterLoc() {
    }
    
    public GetNearestMasterLoc(java.lang.Float arg0, java.lang.Float arg1, java.lang.Integer arg2) {
        this.arg0 = arg0;
        this.arg1 = arg1;
        this.arg2 = arg2;
    }
    
    public java.lang.Float getArg0() {
        return arg0;
    }
    
    public void setArg0(java.lang.Float arg0) {
        this.arg0 = arg0;
    }
    
    public java.lang.Float getArg1() {
        return arg1;
    }
    
    public void setArg1(java.lang.Float arg1) {
        this.arg1 = arg1;
    }
    
    public java.lang.Integer getArg2() {
        return arg2;
    }
    
    public void setArg2(java.lang.Integer arg2) {
        this.arg2 = arg2;
    }
}
