// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class HourlyForecastWS {
    protected java.lang.String CPOS;
    protected java.lang.String clds;
    protected java.lang.String DHlclValTm;
    protected java.lang.String dow;
    protected java.lang.String dwptC;
    protected java.lang.String dwptF;
    protected java.lang.String fcstValDay;
    protected java.lang.String fcstValGMT;
    protected java.lang.String fcstValTm;
    protected java.lang.String glfCat;
    protected java.lang.String glfIdx;
    protected java.lang.String HIC;
    protected java.lang.String HIF;
    protected com.classmeteo.ws.HourlyForecastPKWS hourlyForecastPK;
    protected java.lang.String locValDay;
    protected java.lang.String locValTm;
    protected java.lang.String POP;
    protected java.lang.String procTm;
    protected java.lang.String RH;
    protected java.lang.String sky;
    protected java.lang.String skyX;
    protected java.lang.String snsblWx;
    protected java.lang.String stnNm;
    protected java.lang.String TSnsblWx;
    protected java.lang.String tmpC;
    protected java.lang.String tmpF;
    protected java.lang.String uvDes;
    protected java.lang.String uvIdx;
    protected java.lang.String uvIdxRw;
    protected java.lang.String uvWrn;
    protected java.lang.String visK;
    protected java.lang.String visM;
    protected java.lang.String WCC;
    protected java.lang.String WCF;
    protected java.lang.String WDir;
    protected java.lang.String WDirAsc;
    protected java.lang.String WSpdK;
    protected java.lang.String WSpdKn;
    protected java.lang.String WSpdM;
    protected java.lang.String wrlsWx;
    
    public HourlyForecastWS() {
    }
    
    public HourlyForecastWS(java.lang.String CPOS, java.lang.String clds, java.lang.String DHlclValTm, java.lang.String dow, java.lang.String dwptC, java.lang.String dwptF, java.lang.String fcstValDay, java.lang.String fcstValGMT, java.lang.String fcstValTm, java.lang.String glfCat, java.lang.String glfIdx, java.lang.String HIC, java.lang.String HIF, com.classmeteo.ws.HourlyForecastPKWS hourlyForecastPK, java.lang.String locValDay, java.lang.String locValTm, java.lang.String POP, java.lang.String procTm, java.lang.String RH, java.lang.String sky, java.lang.String skyX, java.lang.String snsblWx, java.lang.String stnNm, java.lang.String TSnsblWx, java.lang.String tmpC, java.lang.String tmpF, java.lang.String uvDes, java.lang.String uvIdx, java.lang.String uvIdxRw, java.lang.String uvWrn, java.lang.String visK, java.lang.String visM, java.lang.String WCC, java.lang.String WCF, java.lang.String WDir, java.lang.String WDirAsc, java.lang.String WSpdK, java.lang.String WSpdKn, java.lang.String WSpdM, java.lang.String wrlsWx) {
        this.CPOS = CPOS;
        this.clds = clds;
        this.DHlclValTm = DHlclValTm;
        this.dow = dow;
        this.dwptC = dwptC;
        this.dwptF = dwptF;
        this.fcstValDay = fcstValDay;
        this.fcstValGMT = fcstValGMT;
        this.fcstValTm = fcstValTm;
        this.glfCat = glfCat;
        this.glfIdx = glfIdx;
        this.HIC = HIC;
        this.HIF = HIF;
        this.hourlyForecastPK = hourlyForecastPK;
        this.locValDay = locValDay;
        this.locValTm = locValTm;
        this.POP = POP;
        this.procTm = procTm;
        this.RH = RH;
        this.sky = sky;
        this.skyX = skyX;
        this.snsblWx = snsblWx;
        this.stnNm = stnNm;
        this.TSnsblWx = TSnsblWx;
        this.tmpC = tmpC;
        this.tmpF = tmpF;
        this.uvDes = uvDes;
        this.uvIdx = uvIdx;
        this.uvIdxRw = uvIdxRw;
        this.uvWrn = uvWrn;
        this.visK = visK;
        this.visM = visM;
        this.WCC = WCC;
        this.WCF = WCF;
        this.WDir = WDir;
        this.WDirAsc = WDirAsc;
        this.WSpdK = WSpdK;
        this.WSpdKn = WSpdKn;
        this.WSpdM = WSpdM;
        this.wrlsWx = wrlsWx;
    }
    
    public java.lang.String getCPOS() {
        return CPOS;
    }
    
    public void setCPOS(java.lang.String CPOS) {
        this.CPOS = CPOS;
    }
    
    public java.lang.String getClds() {
        return clds;
    }
    
    public void setClds(java.lang.String clds) {
        this.clds = clds;
    }
    
    public java.lang.String getDHlclValTm() {
        return DHlclValTm;
    }
    
    public void setDHlclValTm(java.lang.String DHlclValTm) {
        this.DHlclValTm = DHlclValTm;
    }
    
    public java.lang.String getDow() {
        return dow;
    }
    
    public void setDow(java.lang.String dow) {
        this.dow = dow;
    }
    
    public java.lang.String getDwptC() {
        return dwptC;
    }
    
    public void setDwptC(java.lang.String dwptC) {
        this.dwptC = dwptC;
    }
    
    public java.lang.String getDwptF() {
        return dwptF;
    }
    
    public void setDwptF(java.lang.String dwptF) {
        this.dwptF = dwptF;
    }
    
    public java.lang.String getFcstValDay() {
        return fcstValDay;
    }
    
    public void setFcstValDay(java.lang.String fcstValDay) {
        this.fcstValDay = fcstValDay;
    }
    
    public java.lang.String getFcstValGMT() {
        return fcstValGMT;
    }
    
    public void setFcstValGMT(java.lang.String fcstValGMT) {
        this.fcstValGMT = fcstValGMT;
    }
    
    public java.lang.String getFcstValTm() {
        return fcstValTm;
    }
    
    public void setFcstValTm(java.lang.String fcstValTm) {
        this.fcstValTm = fcstValTm;
    }
    
    public java.lang.String getGlfCat() {
        return glfCat;
    }
    
    public void setGlfCat(java.lang.String glfCat) {
        this.glfCat = glfCat;
    }
    
    public java.lang.String getGlfIdx() {
        return glfIdx;
    }
    
    public void setGlfIdx(java.lang.String glfIdx) {
        this.glfIdx = glfIdx;
    }
    
    public java.lang.String getHIC() {
        return HIC;
    }
    
    public void setHIC(java.lang.String HIC) {
        this.HIC = HIC;
    }
    
    public java.lang.String getHIF() {
        return HIF;
    }
    
    public void setHIF(java.lang.String HIF) {
        this.HIF = HIF;
    }
    
    public com.classmeteo.ws.HourlyForecastPKWS getHourlyForecastPK() {
        return hourlyForecastPK;
    }
    
    public void setHourlyForecastPK(com.classmeteo.ws.HourlyForecastPKWS hourlyForecastPK) {
        this.hourlyForecastPK = hourlyForecastPK;
    }
    
    public java.lang.String getLocValDay() {
        return locValDay;
    }
    
    public void setLocValDay(java.lang.String locValDay) {
        this.locValDay = locValDay;
    }
    
    public java.lang.String getLocValTm() {
        return locValTm;
    }
    
    public void setLocValTm(java.lang.String locValTm) {
        this.locValTm = locValTm;
    }
    
    public java.lang.String getPOP() {
        return POP;
    }
    
    public void setPOP(java.lang.String POP) {
        this.POP = POP;
    }
    
    public java.lang.String getProcTm() {
        return procTm;
    }
    
    public void setProcTm(java.lang.String procTm) {
        this.procTm = procTm;
    }
    
    public java.lang.String getRH() {
        return RH;
    }
    
    public void setRH(java.lang.String RH) {
        this.RH = RH;
    }
    
    public java.lang.String getSky() {
        return sky;
    }
    
    public void setSky(java.lang.String sky) {
        this.sky = sky;
    }
    
    public java.lang.String getSkyX() {
        return skyX;
    }
    
    public void setSkyX(java.lang.String skyX) {
        this.skyX = skyX;
    }
    
    public java.lang.String getSnsblWx() {
        return snsblWx;
    }
    
    public void setSnsblWx(java.lang.String snsblWx) {
        this.snsblWx = snsblWx;
    }
    
    public java.lang.String getStnNm() {
        return stnNm;
    }
    
    public void setStnNm(java.lang.String stnNm) {
        this.stnNm = stnNm;
    }
    
    public java.lang.String getTSnsblWx() {
        return TSnsblWx;
    }
    
    public void setTSnsblWx(java.lang.String TSnsblWx) {
        this.TSnsblWx = TSnsblWx;
    }
    
    public java.lang.String getTmpC() {
        return tmpC;
    }
    
    public void setTmpC(java.lang.String tmpC) {
        this.tmpC = tmpC;
    }
    
    public java.lang.String getTmpF() {
        return tmpF;
    }
    
    public void setTmpF(java.lang.String tmpF) {
        this.tmpF = tmpF;
    }
    
    public java.lang.String getUvDes() {
        return uvDes;
    }
    
    public void setUvDes(java.lang.String uvDes) {
        this.uvDes = uvDes;
    }
    
    public java.lang.String getUvIdx() {
        return uvIdx;
    }
    
    public void setUvIdx(java.lang.String uvIdx) {
        this.uvIdx = uvIdx;
    }
    
    public java.lang.String getUvIdxRw() {
        return uvIdxRw;
    }
    
    public void setUvIdxRw(java.lang.String uvIdxRw) {
        this.uvIdxRw = uvIdxRw;
    }
    
    public java.lang.String getUvWrn() {
        return uvWrn;
    }
    
    public void setUvWrn(java.lang.String uvWrn) {
        this.uvWrn = uvWrn;
    }
    
    public java.lang.String getVisK() {
        return visK;
    }
    
    public void setVisK(java.lang.String visK) {
        this.visK = visK;
    }
    
    public java.lang.String getVisM() {
        return visM;
    }
    
    public void setVisM(java.lang.String visM) {
        this.visM = visM;
    }
    
    public java.lang.String getWCC() {
        return WCC;
    }
    
    public void setWCC(java.lang.String WCC) {
        this.WCC = WCC;
    }
    
    public java.lang.String getWCF() {
        return WCF;
    }
    
    public void setWCF(java.lang.String WCF) {
        this.WCF = WCF;
    }
    
    public java.lang.String getWDir() {
        return WDir;
    }
    
    public void setWDir(java.lang.String WDir) {
        this.WDir = WDir;
    }
    
    public java.lang.String getWDirAsc() {
        return WDirAsc;
    }
    
    public void setWDirAsc(java.lang.String WDirAsc) {
        this.WDirAsc = WDirAsc;
    }
    
    public java.lang.String getWSpdK() {
        return WSpdK;
    }
    
    public void setWSpdK(java.lang.String WSpdK) {
        this.WSpdK = WSpdK;
    }
    
    public java.lang.String getWSpdKn() {
        return WSpdKn;
    }
    
    public void setWSpdKn(java.lang.String WSpdKn) {
        this.WSpdKn = WSpdKn;
    }
    
    public java.lang.String getWSpdM() {
        return WSpdM;
    }
    
    public void setWSpdM(java.lang.String WSpdM) {
        this.WSpdM = WSpdM;
    }
    
    public java.lang.String getWrlsWx() {
        return wrlsWx;
    }
    
    public void setWrlsWx(java.lang.String wrlsWx) {
        this.wrlsWx = wrlsWx;
    }
}
