// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class HourlyForecastPKWS {
    protected java.lang.String coopId;
    protected int hrNum;
    
    public HourlyForecastPKWS() {
    }
    
    public HourlyForecastPKWS(java.lang.String coopId, int hrNum) {
        this.coopId = coopId;
        this.hrNum = hrNum;
    }
    
    public java.lang.String getCoopId() {
        return coopId;
    }
    
    public void setCoopId(java.lang.String coopId) {
        this.coopId = coopId;
    }
    
    public int getHrNum() {
        return hrNum;
    }
    
    public void setHrNum(int hrNum) {
        this.hrNum = hrNum;
    }
}
