// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class IntradayForecastPKWS {
    protected java.lang.String coopId;
    protected int dyPrtNum;
    
    public IntradayForecastPKWS() {
    }
    
    public IntradayForecastPKWS(java.lang.String coopId, int dyPrtNum) {
        this.coopId = coopId;
        this.dyPrtNum = dyPrtNum;
    }
    
    public java.lang.String getCoopId() {
        return coopId;
    }
    
    public void setCoopId(java.lang.String coopId) {
        this.coopId = coopId;
    }
    
    public int getDyPrtNum() {
        return dyPrtNum;
    }
    
    public void setDyPrtNum(int dyPrtNum) {
        this.dyPrtNum = dyPrtNum;
    }
}
