// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package com.classmeteo.ws;


public class IntradayForecastWS {
    protected java.lang.String clds;
    protected java.lang.String dow;
    protected java.lang.String dyPrtNm;
    protected java.lang.String fcstValDay;
    protected java.lang.String fcstValGMT;
    protected java.lang.String fcstValTm;
    protected com.classmeteo.ws.IntradayForecastPKWS intradayForecastPK;
    protected java.lang.String locValDay;
    protected java.lang.String locValTm;
    protected java.lang.String POP;
    protected java.lang.String procTm;
    protected java.lang.String RH;
    protected java.lang.String sky;
    protected java.lang.String skyX;
    protected java.lang.String snsblWx;
    protected java.lang.String stnNm;
    protected java.lang.String TSnsblWx;
    protected java.lang.String tmpC;
    protected java.lang.String tmpF;
    protected java.lang.String WDir;
    protected java.lang.String WDirAsc;
    protected java.lang.String WSpdK;
    protected java.lang.String WSpdKn;
    protected java.lang.String WSpdM;
    protected java.lang.String wrlsWx;
    
    public IntradayForecastWS() {
    }
    
    public IntradayForecastWS(java.lang.String clds, java.lang.String dow, java.lang.String dyPrtNm, java.lang.String fcstValDay, java.lang.String fcstValGMT, java.lang.String fcstValTm, com.classmeteo.ws.IntradayForecastPKWS intradayForecastPK, java.lang.String locValDay, java.lang.String locValTm, java.lang.String POP, java.lang.String procTm, java.lang.String RH, java.lang.String sky, java.lang.String skyX, java.lang.String snsblWx, java.lang.String stnNm, java.lang.String TSnsblWx, java.lang.String tmpC, java.lang.String tmpF, java.lang.String WDir, java.lang.String WDirAsc, java.lang.String WSpdK, java.lang.String WSpdKn, java.lang.String WSpdM, java.lang.String wrlsWx) {
        this.clds = clds;
        this.dow = dow;
        this.dyPrtNm = dyPrtNm;
        this.fcstValDay = fcstValDay;
        this.fcstValGMT = fcstValGMT;
        this.fcstValTm = fcstValTm;
        this.intradayForecastPK = intradayForecastPK;
        this.locValDay = locValDay;
        this.locValTm = locValTm;
        this.POP = POP;
        this.procTm = procTm;
        this.RH = RH;
        this.sky = sky;
        this.skyX = skyX;
        this.snsblWx = snsblWx;
        this.stnNm = stnNm;
        this.TSnsblWx = TSnsblWx;
        this.tmpC = tmpC;
        this.tmpF = tmpF;
        this.WDir = WDir;
        this.WDirAsc = WDirAsc;
        this.WSpdK = WSpdK;
        this.WSpdKn = WSpdKn;
        this.WSpdM = WSpdM;
        this.wrlsWx = wrlsWx;
    }
    
    public java.lang.String getClds() {
        return clds;
    }
    
    public void setClds(java.lang.String clds) {
        this.clds = clds;
    }
    
    public java.lang.String getDow() {
        return dow;
    }
    
    public void setDow(java.lang.String dow) {
        this.dow = dow;
    }
    
    public java.lang.String getDyPrtNm() {
        return dyPrtNm;
    }
    
    public void setDyPrtNm(java.lang.String dyPrtNm) {
        this.dyPrtNm = dyPrtNm;
    }
    
    public java.lang.String getFcstValDay() {
        return fcstValDay;
    }
    
    public void setFcstValDay(java.lang.String fcstValDay) {
        this.fcstValDay = fcstValDay;
    }
    
    public java.lang.String getFcstValGMT() {
        return fcstValGMT;
    }
    
    public void setFcstValGMT(java.lang.String fcstValGMT) {
        this.fcstValGMT = fcstValGMT;
    }
    
    public java.lang.String getFcstValTm() {
        return fcstValTm;
    }
    
    public void setFcstValTm(java.lang.String fcstValTm) {
        this.fcstValTm = fcstValTm;
    }
    
    public com.classmeteo.ws.IntradayForecastPKWS getIntradayForecastPK() {
        return intradayForecastPK;
    }
    
    public void setIntradayForecastPK(com.classmeteo.ws.IntradayForecastPKWS intradayForecastPK) {
        this.intradayForecastPK = intradayForecastPK;
    }
    
    public java.lang.String getLocValDay() {
        return locValDay;
    }
    
    public void setLocValDay(java.lang.String locValDay) {
        this.locValDay = locValDay;
    }
    
    public java.lang.String getLocValTm() {
        return locValTm;
    }
    
    public void setLocValTm(java.lang.String locValTm) {
        this.locValTm = locValTm;
    }
    
    public java.lang.String getPOP() {
        return POP;
    }
    
    public void setPOP(java.lang.String POP) {
        this.POP = POP;
    }
    
    public java.lang.String getProcTm() {
        return procTm;
    }
    
    public void setProcTm(java.lang.String procTm) {
        this.procTm = procTm;
    }
    
    public java.lang.String getRH() {
        return RH;
    }
    
    public void setRH(java.lang.String RH) {
        this.RH = RH;
    }
    
    public java.lang.String getSky() {
        return sky;
    }
    
    public void setSky(java.lang.String sky) {
        this.sky = sky;
    }
    
    public java.lang.String getSkyX() {
        return skyX;
    }
    
    public void setSkyX(java.lang.String skyX) {
        this.skyX = skyX;
    }
    
    public java.lang.String getSnsblWx() {
        return snsblWx;
    }
    
    public void setSnsblWx(java.lang.String snsblWx) {
        this.snsblWx = snsblWx;
    }
    
    public java.lang.String getStnNm() {
        return stnNm;
    }
    
    public void setStnNm(java.lang.String stnNm) {
        this.stnNm = stnNm;
    }
    
    public java.lang.String getTSnsblWx() {
        return TSnsblWx;
    }
    
    public void setTSnsblWx(java.lang.String TSnsblWx) {
        this.TSnsblWx = TSnsblWx;
    }
    
    public java.lang.String getTmpC() {
        return tmpC;
    }
    
    public void setTmpC(java.lang.String tmpC) {
        this.tmpC = tmpC;
    }
    
    public java.lang.String getTmpF() {
        return tmpF;
    }
    
    public void setTmpF(java.lang.String tmpF) {
        this.tmpF = tmpF;
    }
    
    public java.lang.String getWDir() {
        return WDir;
    }
    
    public void setWDir(java.lang.String WDir) {
        this.WDir = WDir;
    }
    
    public java.lang.String getWDirAsc() {
        return WDirAsc;
    }
    
    public void setWDirAsc(java.lang.String WDirAsc) {
        this.WDirAsc = WDirAsc;
    }
    
    public java.lang.String getWSpdK() {
        return WSpdK;
    }
    
    public void setWSpdK(java.lang.String WSpdK) {
        this.WSpdK = WSpdK;
    }
    
    public java.lang.String getWSpdKn() {
        return WSpdKn;
    }
    
    public void setWSpdKn(java.lang.String WSpdKn) {
        this.WSpdKn = WSpdKn;
    }
    
    public java.lang.String getWSpdM() {
        return WSpdM;
    }
    
    public void setWSpdM(java.lang.String WSpdM) {
        this.WSpdM = WSpdM;
    }
    
    public java.lang.String getWrlsWx() {
        return wrlsWx;
    }
    
    public void setWrlsWx(java.lang.String wrlsWx) {
        this.wrlsWx = wrlsWx;
    }
}
